# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpost',
            name='pub_date',
        ),
    ]
