# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_answerpost_answer_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.QuestionPost')),
            ],
        ),
        migrations.RemoveField(
            model_name='answerpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='AnswerPost',
        ),
    ]
