# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_questionpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpost',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
