# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_registration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='activated',
            field=models.BooleanField(default=0),
        ),
    ]
