# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_registration_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='file',
            field=models.ImageField(upload_to=b''),
        ),
    ]
