# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_questionpost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='file',
            field=models.FileField(default=None, upload_to=b'forum/media/pictures/'),
        ),
    ]
