# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_answerpost_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpost',
            name='answerCreated',
        ),
        migrations.RemoveField(
            model_name='answerpost',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answerpost',
            name='link',
        ),
        migrations.AddField(
            model_name='answerpost',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerpost',
            name='author',
            field=models.CharField(default=b'FloDeBo', max_length=200),
        ),
        migrations.AddField(
            model_name='answerpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answerpost',
            name='post',
            field=models.ForeignKey(default=b'Post', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.QuestionPost'),
        ),
        migrations.AddField(
            model_name='answerpost',
            name='text',
            field=models.TextField(default=b'FloDeBo'),
        ),
    ]
